routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth.basic']], function () {
    Route::resource('order', 'OrderController');
    Route::resource('goods', 'GoodsController');
});

app/Models/Advert.php
<?php
namespace App\Models;

class Advert extends \Eloquent
{

    public function orders() {
        return $this->hasMany('App\Models\Order');
    }

    public static function list() {
        $adverts_list = [];
        foreach (Advert::all() as  $item) {
            $adverts_list[$item->id] = $item->first_name.' '.$item->last_name.' / '.$item->login;
        }

        return $adverts_list;
    }

}

app/Models/Good.php
<?php
namespace App\Models;

class Good extends \Eloquent
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'goods';

    protected $fillable = array('name', 'price', 'advert_id');

    public static function rules(){
        return [
            'name'      => 'required',
            'price'     => 'required|numeric',
            'advert_id' => 'required|exists:adverts,id',
        ];
    }

    public function advert(){
        return $this->belongsTo('App\Models\Advert');
    }

    public function orders() {
        return $this->hasMany('App\Models\Order');
    }
}

app/Models/Order.php
<?php
namespace App\Models;

class Order extends \Eloquent
{
    public function status(){
        return $this->belongsTo('App\Models\Status');
    }

    public function good(){
        return $this->belongsTo('App\Models\Good', 'good_id');
    }

}

app/Models/Status.php
<?php
namespace App\Models;

class Status extends \Eloquent
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'status';


    /**
     * Возвращает массив статусов
     * @return array
     */
    public static function list(){

        $list = [];
        foreach (self::all() as $item) {
            $list[$item->slug] = $item->name;
        }

        return $list;
    }

    public function orders() {
        return $this->hasMany('App\Models\Order');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GoodsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Good;
use App\Models\Advert;
class GoodsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $list = Good::orderBy('name', 'asc')->get();



        return view('goods.list', ['list' => $list, ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('goods.add',['adverts_list' => Advert::list(), 'mode' => 'add']);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, Good::rules());

         $good = Good::create([
             'name'      => $request->input('name'),
             'price'     => $request->input('price'),
             'advert_id' => $request->input('advert_id')
         ]);

         return redirect(route('goods.index'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $good = Good::find($id);

        if( !$good ){
            return redirect(route('goods.index'));
        }
        return view('goods.edit',['adverts_list' => Advert::list(), 'mode' => 'edit', 'good'=> $good]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         //
         $this->validate($request, Good::rules());
         $good = Good::find($id);

         if( $good ){
            $good->fill([
                 'name'      => $request->input('name'),
                 'price'     => $request->input('price'),
                 'advert_id' => $request->input('advert_id')
            ])->save();
         }

         return redirect(route('goods.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Order;

class OrderController extends Controller
{
    /**
     * Список заказов
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $list = Order::orderBy('created_at', 'desc')->get();
        return view('orders.list', ['list' => $list]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/common/menu.blade.php
<div>
    <ul class="menu list-unstyled list-inline">
      <li <?=(\Route::getCurrentRoute()->uri()=='order'?'class="active"':'')?>><a href="<?=route('order.index')?>">Заказы</a></li>
      <li <?=(\Route::getCurrentRoute()->uri()=='goods'?'class="active"':'')?>><a href="<?=route('goods.index')?>">Товары</a></li>
    </ul>
</div>

resources/views/common/meta.blade.php
<title>Test Task</title>
<meta charset="utf-8" />
<link href="http://yastatic.net/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
<link href="/css/style.css" rel="stylesheet" media="all">

<script src="http://yastatic.net/jquery/2.1.4/jquery.min.js"></script>
<script src="http://yastatic.net/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<link href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css" rel="stylesheet" media="all">
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>

resources/views/goods/add.blade.php
@extends('layouts.main')
@section('content')


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<h4>Добавить товар</h4>


<div>

    <?= Former::open(route('goods.store'))->method('POST') ?>
    {!! csrf_field() !!}
    <?= Former::text('name')->label('Название') ?><br>

    <?= Former::text('price')->label('Цена') ?><br>

    <?= Former::select('advert_id')->label('Рекламодатель')->options($adverts_list, 1)?>

    <div class="clearfix">
    <button type="submit" class="pull-right">Сохранить</button>
    </div>
</div>
<?= Former::close() ?>
@endsection

resources/views/goods/edit.blade.php
@extends('layouts.main')
@section('content')


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<h4>Редактировать товар</h4>
<div>

    <?= Former::open(route('goods.update', ['id'=>$good->id]))->method('PUT') ?>
    {!! csrf_field() !!}
    <?= Former::text('name')->label('Название')->value($good->name) ?><br>

    <?= Former::text('price')->label('Цена')->value($good->price)?><br>

    <?= Former::select('advert_id')->label('Рекламодатель')->options($adverts_list, $good->advert_id)?>

    <div class="clearfix">
    <button type="submit" class="pull-right">Сохранить</button>
    </div>
</div>
<?= Former::close() ?>
@endsection

resources/views/goods/list.blade.php
@extends('layouts.main')
@section('content')
    <div class="clearfix" style="margin-bottom:20px;">
        <a href="<?=route('goods.create')?>" class="btn btn-success pull-right">Добавить товар</a>
    </div>
    <?php if($list->count()):?>
        <table class="table">
            <thead>
                    <tr>
                        <th>#</th>
                        <th>Название</th>
                        <th>Цена</th>
                        <th>Рекламодатель</th>
                        <th></th>
                    </tr>

            </thead>
            <tbody>
                <?php foreach ($list as $item):?>
                    <tr>
                        <td><?=$item->id?></td>
                        <td><?=$item->name?></td>
                        <td><?=$item->price?></td>
                        <td>
                            <a href="#"><?=$item->advert->last_name?> <?=$item->advert->first_name?></a><br>
                            <?=$item->advert->login?>
                        </td>
                        <td>
                            <a href="<?=route('goods.edit',['id'=>$item->id])?>">Редактировать</a>
                        </td>

                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>

<script>
    $(document).ready(function(){
        $('.table').DataTable({
             "pageLength": 2,
             "language": {
                 "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Russian.json",

             }
        });
    });
</script>
    <?php else :?>
        <div class="empty_message">Заказов пока не создано</div>
    <?php endif;?>



@endsection

resources/views/layouts/main.blade.php
<!doctype html>
<html>
    <head>
        @section('meta')
            @include('common.meta')
        @show
    </head>
    <body>
        <div class="content">
            @include('common.menu')

            @yield('content')
        </div>
        @section('scripts')
            @include('common.scripts')
        @show
    </body>
</html>

resources/views/orders/list.blade.php
@extends('layouts.main')
@section('content')

    <?php if($list->count()):?>
        <table class="table">
            <thead>
                    <tr>
                        <th>#</th>
                        <th>Дата</th>
                        <th>Клиент</th>
                        <th>Телефон</th>
                        <th>Товар</th>
                        <th>Статус</th>
                    </tr>

            </thead>
            <tbody>
                <?php foreach ($list as $item):?>
                    <tr>
                        <td><?=$item->id?></td>
                        <td><?=$item->created_at?></td>
                        <td><?=$item->client_name?></td>
                        <td><?=$item->client_phone?></td>
                        <td>
                            <a href="#"><?=$item->good->name?></a><br>
                            <?=$item->good->advert->last_name?> <?=$item->good->advert->first_name?> (<?=$item->good->advert->login?>)
                        </td>
                        <td><?=$item->status()->first()->name?></td>

                    </tr>
                <?php endforeach;?>
            </tbody>
        </table>

        <script>
            $(document).ready(function(){
                $('.table').DataTable({
                     "pageLength": 2,
                     "language": {
                         "url": "//cdn.datatables.net/plug-ins/1.10.12/i18n/Russian.json",

                     }
                });
            });
        </script>
    <?php else :?>
        <div class="empty_message">Заказов пока не создано</div>
    <?php endif;?>

@endsection